### ISSUE TITLE
Does not iterate sections properly

### ISSUE THREAD

**Issue by sylmz** [Zeesky-code/pdf-extractor#1]
The below code runs the same section at all.

https://github.com/Zeesky-code/pdf-extractor/blob/2c5b445eef844b864e0fc86014d41d9beca2a7e1/src/main/java/Extractor.java#L41-L44

Also, PreparedStatements can be used over and over thus it is not needed to create the same prepared statement inside the loop.

**Comment by Zeesky-code** [comment]
Yes, I set it to run the same section while debugging and I forgot to change that after.  I would implement the fixes.

**Comment by Zeesky-code** [comment]
I have implemented the changes with #2
