### ISSUE TITLE
Must be excluded page headers and footers from the content of judgment

### ISSUE THREAD

**Issue by sylmz** [Zeesky-code/pdf-extractor#4]
This is another important part of the task. Text of a judgment can include the metadata such as court name, chamber name, docket no, and decision no because this data is also a part of judgment, but the text cannot contain the page headers and footers which are part of publication.  The headers and footers of page, and section titles must be excluded.

**Comment by Zeesky-code** [comment]
Fixed this issue with https://github.com/Zeesky-code/pdf-extractor/commit/09dea61ec2ab8cce3baeabf05a2eff220101051c
